from models.alexnet_1 import alexnet_1
from models.res18_1 import res18_1
from models.res50_1 import res50_1
from models.mobilenet_1 import mobilenet_1
from models.shufflenet_1 import shufflenet_1
from models.deepspeech_1 import deepspeech_1
from models.transformer_1 import transformer_1
from models.gnmt_1 import gnmt_1
from models.lstm_1 import lstm_1
from models.bert_1 import bert_1
from models.vae_1 import vae_1
from models.m5_1 import m5_1
from models.alexnet_2 import alexnet_2
from models.res18_2 import res18_2
from models.res50_2 import res50_2
from models.mobilenet_2 import mobilenet_2
from models.shufflenet_2 import shufflenet_2
from models.deepspeech_2 import deepspeech_2
from models.transformer_2 import transformer_2
from models.gnmt_2 import gnmt_2
from models.lstm_2 import lstm_2
from models.alexnet_4 import alexnet_4
from models.res18_4 import res18_4
from models.res50_4 import res50_4
from models.mobilenet_4 import mobilenet_4
from models.shufflenet_4 import shufflenet_4
from models.deepspeech_4 import deepspeech_4
from models.transformer_4 import transformer_4
from models.gnmt_4 import gnmt_4
from models.lstm_4 import lstm_4
from models.shufflenet_12 import shufflenet_12
