from models.alexnet_1 import alexnet_1
from models.res18_1 import res18_1
from models.res50_1 import res50_1
from models.mobilenet_1 import mobilenet_1
from models.shufflenet_1 import shufflenet_1
from models.deepspeech_1 import deepspeech_1
from models.transformer_1 import transformer_1
from models.gnmt_1 import gnmt_1
from models.lstm_1 import lstm_1
from models.bert_1 import bert_1
from models.vae_1 import vae_1
from models.m5_1 import m5_1
